// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InstantMessageInfo.proto

package com.sunlearning.messanger.proto;

public final class ProtoMessage {
  private ProtoMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InstantMessageInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InstantMessageInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string MessageId = 1;</code>
     */
    java.lang.String getMessageId();
    /**
     * <code>string MessageId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <code>string SenderCode = 2;</code>
     */
    java.lang.String getSenderCode();
    /**
     * <code>string SenderCode = 2;</code>
     */
    com.google.protobuf.ByteString
        getSenderCodeBytes();

    /**
     * <code>string SenderName = 3;</code>
     */
    java.lang.String getSenderName();
    /**
     * <code>string SenderName = 3;</code>
     */
    com.google.protobuf.ByteString
        getSenderNameBytes();

    /**
     * <code>string SenderAvatar = 4;</code>
     */
    java.lang.String getSenderAvatar();
    /**
     * <code>string SenderAvatar = 4;</code>
     */
    com.google.protobuf.ByteString
        getSenderAvatarBytes();

    /**
     * <code>string ReceiverCode = 5;</code>
     */
    java.lang.String getReceiverCode();
    /**
     * <code>string ReceiverCode = 5;</code>
     */
    com.google.protobuf.ByteString
        getReceiverCodeBytes();

    /**
     * <code>string ReceiverName = 6;</code>
     */
    java.lang.String getReceiverName();
    /**
     * <code>string ReceiverName = 6;</code>
     */
    com.google.protobuf.ByteString
        getReceiverNameBytes();

    /**
     * <code>string ReceiverAvatar = 7;</code>
     */
    java.lang.String getReceiverAvatar();
    /**
     * <code>string ReceiverAvatar = 7;</code>
     */
    com.google.protobuf.ByteString
        getReceiverAvatarBytes();

    /**
     * <code>string ReceiverType = 8;</code>
     */
    java.lang.String getReceiverType();
    /**
     * <code>string ReceiverType = 8;</code>
     */
    com.google.protobuf.ByteString
        getReceiverTypeBytes();

    /**
     * <code>string ContentType = 9;</code>
     */
    java.lang.String getContentType();
    /**
     * <code>string ContentType = 9;</code>
     */
    com.google.protobuf.ByteString
        getContentTypeBytes();

    /**
     * <code>string StringContent = 10;</code>
     */
    java.lang.String getStringContent();
    /**
     * <code>string StringContent = 10;</code>
     */
    com.google.protobuf.ByteString
        getStringContentBytes();

    /**
     * <code>bytes BytesContent = 11;</code>
     */
    com.google.protobuf.ByteString getBytesContent();

    /**
     * <code>int64 MessageTime = 12;</code>
     */
    long getMessageTime();

    /**
     * <code>string FileName = 13;</code>
     */
    java.lang.String getFileName();
    /**
     * <code>string FileName = 13;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>string OldMessageId = 14;</code>
     */
    java.lang.String getOldMessageId();
    /**
     * <code>string OldMessageId = 14;</code>
     */
    com.google.protobuf.ByteString
        getOldMessageIdBytes();

    /**
     * <code>string ChatCode = 15;</code>
     */
    java.lang.String getChatCode();
    /**
     * <code>string ChatCode = 15;</code>
     */
    com.google.protobuf.ByteString
        getChatCodeBytes();

    /**
     * <code>string ChatName = 16;</code>
     */
    java.lang.String getChatName();
    /**
     * <code>string ChatName = 16;</code>
     */
    com.google.protobuf.ByteString
        getChatNameBytes();

    /**
     * <code>string ChatAvatar = 17;</code>
     */
    java.lang.String getChatAvatar();
    /**
     * <code>string ChatAvatar = 17;</code>
     */
    com.google.protobuf.ByteString
        getChatAvatarBytes();
  }
  /**
   * Protobuf type {@code InstantMessageInfo}
   */
  public  static final class InstantMessageInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:InstantMessageInfo)
      InstantMessageInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InstantMessageInfo.newBuilder() to construct.
    private InstantMessageInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InstantMessageInfo() {
      messageId_ = "";
      senderCode_ = "";
      senderName_ = "";
      senderAvatar_ = "";
      receiverCode_ = "";
      receiverName_ = "";
      receiverAvatar_ = "";
      receiverType_ = "";
      contentType_ = "";
      stringContent_ = "";
      bytesContent_ = com.google.protobuf.ByteString.EMPTY;
      messageTime_ = 0L;
      fileName_ = "";
      oldMessageId_ = "";
      chatCode_ = "";
      chatName_ = "";
      chatAvatar_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InstantMessageInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              messageId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              senderCode_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              senderName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              senderAvatar_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              receiverCode_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              receiverName_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              receiverAvatar_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              receiverType_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              contentType_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              stringContent_ = s;
              break;
            }
            case 90: {

              bytesContent_ = input.readBytes();
              break;
            }
            case 96: {

              messageTime_ = input.readInt64();
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              fileName_ = s;
              break;
            }
            case 114: {
              java.lang.String s = input.readStringRequireUtf8();

              oldMessageId_ = s;
              break;
            }
            case 122: {
              java.lang.String s = input.readStringRequireUtf8();

              chatCode_ = s;
              break;
            }
            case 130: {
              java.lang.String s = input.readStringRequireUtf8();

              chatName_ = s;
              break;
            }
            case 138: {
              java.lang.String s = input.readStringRequireUtf8();

              chatAvatar_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sunlearning.messanger.proto.ProtoMessage.internal_static_InstantMessageInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sunlearning.messanger.proto.ProtoMessage.internal_static_InstantMessageInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo.class, com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo.Builder.class);
    }

    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object messageId_;
    /**
     * <code>string MessageId = 1;</code>
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      }
    }
    /**
     * <code>string MessageId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERCODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object senderCode_;
    /**
     * <code>string SenderCode = 2;</code>
     */
    public java.lang.String getSenderCode() {
      java.lang.Object ref = senderCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderCode_ = s;
        return s;
      }
    }
    /**
     * <code>string SenderCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSenderCodeBytes() {
      java.lang.Object ref = senderCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object senderName_;
    /**
     * <code>string SenderName = 3;</code>
     */
    public java.lang.String getSenderName() {
      java.lang.Object ref = senderName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderName_ = s;
        return s;
      }
    }
    /**
     * <code>string SenderName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSenderNameBytes() {
      java.lang.Object ref = senderName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERAVATAR_FIELD_NUMBER = 4;
    private volatile java.lang.Object senderAvatar_;
    /**
     * <code>string SenderAvatar = 4;</code>
     */
    public java.lang.String getSenderAvatar() {
      java.lang.Object ref = senderAvatar_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderAvatar_ = s;
        return s;
      }
    }
    /**
     * <code>string SenderAvatar = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSenderAvatarBytes() {
      java.lang.Object ref = senderAvatar_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderAvatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVERCODE_FIELD_NUMBER = 5;
    private volatile java.lang.Object receiverCode_;
    /**
     * <code>string ReceiverCode = 5;</code>
     */
    public java.lang.String getReceiverCode() {
      java.lang.Object ref = receiverCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverCode_ = s;
        return s;
      }
    }
    /**
     * <code>string ReceiverCode = 5;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverCodeBytes() {
      java.lang.Object ref = receiverCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVERNAME_FIELD_NUMBER = 6;
    private volatile java.lang.Object receiverName_;
    /**
     * <code>string ReceiverName = 6;</code>
     */
    public java.lang.String getReceiverName() {
      java.lang.Object ref = receiverName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverName_ = s;
        return s;
      }
    }
    /**
     * <code>string ReceiverName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverNameBytes() {
      java.lang.Object ref = receiverName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVERAVATAR_FIELD_NUMBER = 7;
    private volatile java.lang.Object receiverAvatar_;
    /**
     * <code>string ReceiverAvatar = 7;</code>
     */
    public java.lang.String getReceiverAvatar() {
      java.lang.Object ref = receiverAvatar_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverAvatar_ = s;
        return s;
      }
    }
    /**
     * <code>string ReceiverAvatar = 7;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverAvatarBytes() {
      java.lang.Object ref = receiverAvatar_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverAvatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVERTYPE_FIELD_NUMBER = 8;
    private volatile java.lang.Object receiverType_;
    /**
     * <code>string ReceiverType = 8;</code>
     */
    public java.lang.String getReceiverType() {
      java.lang.Object ref = receiverType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverType_ = s;
        return s;
      }
    }
    /**
     * <code>string ReceiverType = 8;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverTypeBytes() {
      java.lang.Object ref = receiverType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENTTYPE_FIELD_NUMBER = 9;
    private volatile java.lang.Object contentType_;
    /**
     * <code>string ContentType = 9;</code>
     */
    public java.lang.String getContentType() {
      java.lang.Object ref = contentType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contentType_ = s;
        return s;
      }
    }
    /**
     * <code>string ContentType = 9;</code>
     */
    public com.google.protobuf.ByteString
        getContentTypeBytes() {
      java.lang.Object ref = contentType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STRINGCONTENT_FIELD_NUMBER = 10;
    private volatile java.lang.Object stringContent_;
    /**
     * <code>string StringContent = 10;</code>
     */
    public java.lang.String getStringContent() {
      java.lang.Object ref = stringContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stringContent_ = s;
        return s;
      }
    }
    /**
     * <code>string StringContent = 10;</code>
     */
    public com.google.protobuf.ByteString
        getStringContentBytes() {
      java.lang.Object ref = stringContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BYTESCONTENT_FIELD_NUMBER = 11;
    private com.google.protobuf.ByteString bytesContent_;
    /**
     * <code>bytes BytesContent = 11;</code>
     */
    public com.google.protobuf.ByteString getBytesContent() {
      return bytesContent_;
    }

    public static final int MESSAGETIME_FIELD_NUMBER = 12;
    private long messageTime_;
    /**
     * <code>int64 MessageTime = 12;</code>
     */
    public long getMessageTime() {
      return messageTime_;
    }

    public static final int FILENAME_FIELD_NUMBER = 13;
    private volatile java.lang.Object fileName_;
    /**
     * <code>string FileName = 13;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <code>string FileName = 13;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OLDMESSAGEID_FIELD_NUMBER = 14;
    private volatile java.lang.Object oldMessageId_;
    /**
     * <code>string OldMessageId = 14;</code>
     */
    public java.lang.String getOldMessageId() {
      java.lang.Object ref = oldMessageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        oldMessageId_ = s;
        return s;
      }
    }
    /**
     * <code>string OldMessageId = 14;</code>
     */
    public com.google.protobuf.ByteString
        getOldMessageIdBytes() {
      java.lang.Object ref = oldMessageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oldMessageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHATCODE_FIELD_NUMBER = 15;
    private volatile java.lang.Object chatCode_;
    /**
     * <code>string ChatCode = 15;</code>
     */
    public java.lang.String getChatCode() {
      java.lang.Object ref = chatCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chatCode_ = s;
        return s;
      }
    }
    /**
     * <code>string ChatCode = 15;</code>
     */
    public com.google.protobuf.ByteString
        getChatCodeBytes() {
      java.lang.Object ref = chatCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chatCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHATNAME_FIELD_NUMBER = 16;
    private volatile java.lang.Object chatName_;
    /**
     * <code>string ChatName = 16;</code>
     */
    public java.lang.String getChatName() {
      java.lang.Object ref = chatName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chatName_ = s;
        return s;
      }
    }
    /**
     * <code>string ChatName = 16;</code>
     */
    public com.google.protobuf.ByteString
        getChatNameBytes() {
      java.lang.Object ref = chatName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chatName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHATAVATAR_FIELD_NUMBER = 17;
    private volatile java.lang.Object chatAvatar_;
    /**
     * <code>string ChatAvatar = 17;</code>
     */
    public java.lang.String getChatAvatar() {
      java.lang.Object ref = chatAvatar_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chatAvatar_ = s;
        return s;
      }
    }
    /**
     * <code>string ChatAvatar = 17;</code>
     */
    public com.google.protobuf.ByteString
        getChatAvatarBytes() {
      java.lang.Object ref = chatAvatar_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chatAvatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageId_);
      }
      if (!getSenderCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, senderCode_);
      }
      if (!getSenderNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, senderName_);
      }
      if (!getSenderAvatarBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, senderAvatar_);
      }
      if (!getReceiverCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, receiverCode_);
      }
      if (!getReceiverNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, receiverName_);
      }
      if (!getReceiverAvatarBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, receiverAvatar_);
      }
      if (!getReceiverTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, receiverType_);
      }
      if (!getContentTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, contentType_);
      }
      if (!getStringContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, stringContent_);
      }
      if (!bytesContent_.isEmpty()) {
        output.writeBytes(11, bytesContent_);
      }
      if (messageTime_ != 0L) {
        output.writeInt64(12, messageTime_);
      }
      if (!getFileNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, fileName_);
      }
      if (!getOldMessageIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, oldMessageId_);
      }
      if (!getChatCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, chatCode_);
      }
      if (!getChatNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 16, chatName_);
      }
      if (!getChatAvatarBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 17, chatAvatar_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageId_);
      }
      if (!getSenderCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, senderCode_);
      }
      if (!getSenderNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, senderName_);
      }
      if (!getSenderAvatarBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, senderAvatar_);
      }
      if (!getReceiverCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, receiverCode_);
      }
      if (!getReceiverNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, receiverName_);
      }
      if (!getReceiverAvatarBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, receiverAvatar_);
      }
      if (!getReceiverTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, receiverType_);
      }
      if (!getContentTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, contentType_);
      }
      if (!getStringContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, stringContent_);
      }
      if (!bytesContent_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, bytesContent_);
      }
      if (messageTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, messageTime_);
      }
      if (!getFileNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, fileName_);
      }
      if (!getOldMessageIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, oldMessageId_);
      }
      if (!getChatCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, chatCode_);
      }
      if (!getChatNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, chatName_);
      }
      if (!getChatAvatarBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, chatAvatar_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo)) {
        return super.equals(obj);
      }
      com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo other = (com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo) obj;

      boolean result = true;
      result = result && getMessageId()
          .equals(other.getMessageId());
      result = result && getSenderCode()
          .equals(other.getSenderCode());
      result = result && getSenderName()
          .equals(other.getSenderName());
      result = result && getSenderAvatar()
          .equals(other.getSenderAvatar());
      result = result && getReceiverCode()
          .equals(other.getReceiverCode());
      result = result && getReceiverName()
          .equals(other.getReceiverName());
      result = result && getReceiverAvatar()
          .equals(other.getReceiverAvatar());
      result = result && getReceiverType()
          .equals(other.getReceiverType());
      result = result && getContentType()
          .equals(other.getContentType());
      result = result && getStringContent()
          .equals(other.getStringContent());
      result = result && getBytesContent()
          .equals(other.getBytesContent());
      result = result && (getMessageTime()
          == other.getMessageTime());
      result = result && getFileName()
          .equals(other.getFileName());
      result = result && getOldMessageId()
          .equals(other.getOldMessageId());
      result = result && getChatCode()
          .equals(other.getChatCode());
      result = result && getChatName()
          .equals(other.getChatName());
      result = result && getChatAvatar()
          .equals(other.getChatAvatar());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId().hashCode();
      hash = (37 * hash) + SENDERCODE_FIELD_NUMBER;
      hash = (53 * hash) + getSenderCode().hashCode();
      hash = (37 * hash) + SENDERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSenderName().hashCode();
      hash = (37 * hash) + SENDERAVATAR_FIELD_NUMBER;
      hash = (53 * hash) + getSenderAvatar().hashCode();
      hash = (37 * hash) + RECEIVERCODE_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverCode().hashCode();
      hash = (37 * hash) + RECEIVERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverName().hashCode();
      hash = (37 * hash) + RECEIVERAVATAR_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverAvatar().hashCode();
      hash = (37 * hash) + RECEIVERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverType().hashCode();
      hash = (37 * hash) + CONTENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getContentType().hashCode();
      hash = (37 * hash) + STRINGCONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getStringContent().hashCode();
      hash = (37 * hash) + BYTESCONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getBytesContent().hashCode();
      hash = (37 * hash) + MESSAGETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMessageTime());
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + OLDMESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getOldMessageId().hashCode();
      hash = (37 * hash) + CHATCODE_FIELD_NUMBER;
      hash = (53 * hash) + getChatCode().hashCode();
      hash = (37 * hash) + CHATNAME_FIELD_NUMBER;
      hash = (53 * hash) + getChatName().hashCode();
      hash = (37 * hash) + CHATAVATAR_FIELD_NUMBER;
      hash = (53 * hash) + getChatAvatar().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InstantMessageInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:InstantMessageInfo)
        com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sunlearning.messanger.proto.ProtoMessage.internal_static_InstantMessageInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sunlearning.messanger.proto.ProtoMessage.internal_static_InstantMessageInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo.class, com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo.Builder.class);
      }

      // Construct using com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageId_ = "";

        senderCode_ = "";

        senderName_ = "";

        senderAvatar_ = "";

        receiverCode_ = "";

        receiverName_ = "";

        receiverAvatar_ = "";

        receiverType_ = "";

        contentType_ = "";

        stringContent_ = "";

        bytesContent_ = com.google.protobuf.ByteString.EMPTY;

        messageTime_ = 0L;

        fileName_ = "";

        oldMessageId_ = "";

        chatCode_ = "";

        chatName_ = "";

        chatAvatar_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sunlearning.messanger.proto.ProtoMessage.internal_static_InstantMessageInfo_descriptor;
      }

      @java.lang.Override
      public com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo getDefaultInstanceForType() {
        return com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo build() {
        com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo buildPartial() {
        com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo result = new com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo(this);
        result.messageId_ = messageId_;
        result.senderCode_ = senderCode_;
        result.senderName_ = senderName_;
        result.senderAvatar_ = senderAvatar_;
        result.receiverCode_ = receiverCode_;
        result.receiverName_ = receiverName_;
        result.receiverAvatar_ = receiverAvatar_;
        result.receiverType_ = receiverType_;
        result.contentType_ = contentType_;
        result.stringContent_ = stringContent_;
        result.bytesContent_ = bytesContent_;
        result.messageTime_ = messageTime_;
        result.fileName_ = fileName_;
        result.oldMessageId_ = oldMessageId_;
        result.chatCode_ = chatCode_;
        result.chatName_ = chatName_;
        result.chatAvatar_ = chatAvatar_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo) {
          return mergeFrom((com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo other) {
        if (other == com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo.getDefaultInstance()) return this;
        if (!other.getMessageId().isEmpty()) {
          messageId_ = other.messageId_;
          onChanged();
        }
        if (!other.getSenderCode().isEmpty()) {
          senderCode_ = other.senderCode_;
          onChanged();
        }
        if (!other.getSenderName().isEmpty()) {
          senderName_ = other.senderName_;
          onChanged();
        }
        if (!other.getSenderAvatar().isEmpty()) {
          senderAvatar_ = other.senderAvatar_;
          onChanged();
        }
        if (!other.getReceiverCode().isEmpty()) {
          receiverCode_ = other.receiverCode_;
          onChanged();
        }
        if (!other.getReceiverName().isEmpty()) {
          receiverName_ = other.receiverName_;
          onChanged();
        }
        if (!other.getReceiverAvatar().isEmpty()) {
          receiverAvatar_ = other.receiverAvatar_;
          onChanged();
        }
        if (!other.getReceiverType().isEmpty()) {
          receiverType_ = other.receiverType_;
          onChanged();
        }
        if (!other.getContentType().isEmpty()) {
          contentType_ = other.contentType_;
          onChanged();
        }
        if (!other.getStringContent().isEmpty()) {
          stringContent_ = other.stringContent_;
          onChanged();
        }
        if (other.getBytesContent() != com.google.protobuf.ByteString.EMPTY) {
          setBytesContent(other.getBytesContent());
        }
        if (other.getMessageTime() != 0L) {
          setMessageTime(other.getMessageTime());
        }
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          onChanged();
        }
        if (!other.getOldMessageId().isEmpty()) {
          oldMessageId_ = other.oldMessageId_;
          onChanged();
        }
        if (!other.getChatCode().isEmpty()) {
          chatCode_ = other.chatCode_;
          onChanged();
        }
        if (!other.getChatName().isEmpty()) {
          chatName_ = other.chatName_;
          onChanged();
        }
        if (!other.getChatAvatar().isEmpty()) {
          chatAvatar_ = other.chatAvatar_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object messageId_ = "";
      /**
       * <code>string MessageId = 1;</code>
       */
      public java.lang.String getMessageId() {
        java.lang.Object ref = messageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string MessageId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        java.lang.Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string MessageId = 1;</code>
       */
      public Builder setMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string MessageId = 1;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <code>string MessageId = 1;</code>
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object senderCode_ = "";
      /**
       * <code>string SenderCode = 2;</code>
       */
      public java.lang.String getSenderCode() {
        java.lang.Object ref = senderCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string SenderCode = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSenderCodeBytes() {
        java.lang.Object ref = senderCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string SenderCode = 2;</code>
       */
      public Builder setSenderCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string SenderCode = 2;</code>
       */
      public Builder clearSenderCode() {
        
        senderCode_ = getDefaultInstance().getSenderCode();
        onChanged();
        return this;
      }
      /**
       * <code>string SenderCode = 2;</code>
       */
      public Builder setSenderCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object senderName_ = "";
      /**
       * <code>string SenderName = 3;</code>
       */
      public java.lang.String getSenderName() {
        java.lang.Object ref = senderName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string SenderName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSenderNameBytes() {
        java.lang.Object ref = senderName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string SenderName = 3;</code>
       */
      public Builder setSenderName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string SenderName = 3;</code>
       */
      public Builder clearSenderName() {
        
        senderName_ = getDefaultInstance().getSenderName();
        onChanged();
        return this;
      }
      /**
       * <code>string SenderName = 3;</code>
       */
      public Builder setSenderNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object senderAvatar_ = "";
      /**
       * <code>string SenderAvatar = 4;</code>
       */
      public java.lang.String getSenderAvatar() {
        java.lang.Object ref = senderAvatar_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderAvatar_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string SenderAvatar = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSenderAvatarBytes() {
        java.lang.Object ref = senderAvatar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderAvatar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string SenderAvatar = 4;</code>
       */
      public Builder setSenderAvatar(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderAvatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string SenderAvatar = 4;</code>
       */
      public Builder clearSenderAvatar() {
        
        senderAvatar_ = getDefaultInstance().getSenderAvatar();
        onChanged();
        return this;
      }
      /**
       * <code>string SenderAvatar = 4;</code>
       */
      public Builder setSenderAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderAvatar_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiverCode_ = "";
      /**
       * <code>string ReceiverCode = 5;</code>
       */
      public java.lang.String getReceiverCode() {
        java.lang.Object ref = receiverCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiverCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ReceiverCode = 5;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverCodeBytes() {
        java.lang.Object ref = receiverCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ReceiverCode = 5;</code>
       */
      public Builder setReceiverCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiverCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ReceiverCode = 5;</code>
       */
      public Builder clearReceiverCode() {
        
        receiverCode_ = getDefaultInstance().getReceiverCode();
        onChanged();
        return this;
      }
      /**
       * <code>string ReceiverCode = 5;</code>
       */
      public Builder setReceiverCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiverCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiverName_ = "";
      /**
       * <code>string ReceiverName = 6;</code>
       */
      public java.lang.String getReceiverName() {
        java.lang.Object ref = receiverName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiverName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ReceiverName = 6;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverNameBytes() {
        java.lang.Object ref = receiverName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ReceiverName = 6;</code>
       */
      public Builder setReceiverName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiverName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ReceiverName = 6;</code>
       */
      public Builder clearReceiverName() {
        
        receiverName_ = getDefaultInstance().getReceiverName();
        onChanged();
        return this;
      }
      /**
       * <code>string ReceiverName = 6;</code>
       */
      public Builder setReceiverNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiverName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiverAvatar_ = "";
      /**
       * <code>string ReceiverAvatar = 7;</code>
       */
      public java.lang.String getReceiverAvatar() {
        java.lang.Object ref = receiverAvatar_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiverAvatar_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ReceiverAvatar = 7;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverAvatarBytes() {
        java.lang.Object ref = receiverAvatar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverAvatar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ReceiverAvatar = 7;</code>
       */
      public Builder setReceiverAvatar(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiverAvatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ReceiverAvatar = 7;</code>
       */
      public Builder clearReceiverAvatar() {
        
        receiverAvatar_ = getDefaultInstance().getReceiverAvatar();
        onChanged();
        return this;
      }
      /**
       * <code>string ReceiverAvatar = 7;</code>
       */
      public Builder setReceiverAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiverAvatar_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiverType_ = "";
      /**
       * <code>string ReceiverType = 8;</code>
       */
      public java.lang.String getReceiverType() {
        java.lang.Object ref = receiverType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiverType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ReceiverType = 8;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverTypeBytes() {
        java.lang.Object ref = receiverType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ReceiverType = 8;</code>
       */
      public Builder setReceiverType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiverType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ReceiverType = 8;</code>
       */
      public Builder clearReceiverType() {
        
        receiverType_ = getDefaultInstance().getReceiverType();
        onChanged();
        return this;
      }
      /**
       * <code>string ReceiverType = 8;</code>
       */
      public Builder setReceiverTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiverType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object contentType_ = "";
      /**
       * <code>string ContentType = 9;</code>
       */
      public java.lang.String getContentType() {
        java.lang.Object ref = contentType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contentType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ContentType = 9;</code>
       */
      public com.google.protobuf.ByteString
          getContentTypeBytes() {
        java.lang.Object ref = contentType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contentType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ContentType = 9;</code>
       */
      public Builder setContentType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contentType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ContentType = 9;</code>
       */
      public Builder clearContentType() {
        
        contentType_ = getDefaultInstance().getContentType();
        onChanged();
        return this;
      }
      /**
       * <code>string ContentType = 9;</code>
       */
      public Builder setContentTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        contentType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object stringContent_ = "";
      /**
       * <code>string StringContent = 10;</code>
       */
      public java.lang.String getStringContent() {
        java.lang.Object ref = stringContent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stringContent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string StringContent = 10;</code>
       */
      public com.google.protobuf.ByteString
          getStringContentBytes() {
        java.lang.Object ref = stringContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string StringContent = 10;</code>
       */
      public Builder setStringContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stringContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string StringContent = 10;</code>
       */
      public Builder clearStringContent() {
        
        stringContent_ = getDefaultInstance().getStringContent();
        onChanged();
        return this;
      }
      /**
       * <code>string StringContent = 10;</code>
       */
      public Builder setStringContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stringContent_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bytesContent_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes BytesContent = 11;</code>
       */
      public com.google.protobuf.ByteString getBytesContent() {
        return bytesContent_;
      }
      /**
       * <code>bytes BytesContent = 11;</code>
       */
      public Builder setBytesContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bytesContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes BytesContent = 11;</code>
       */
      public Builder clearBytesContent() {
        
        bytesContent_ = getDefaultInstance().getBytesContent();
        onChanged();
        return this;
      }

      private long messageTime_ ;
      /**
       * <code>int64 MessageTime = 12;</code>
       */
      public long getMessageTime() {
        return messageTime_;
      }
      /**
       * <code>int64 MessageTime = 12;</code>
       */
      public Builder setMessageTime(long value) {
        
        messageTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 MessageTime = 12;</code>
       */
      public Builder clearMessageTime() {
        
        messageTime_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object fileName_ = "";
      /**
       * <code>string FileName = 13;</code>
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string FileName = 13;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string FileName = 13;</code>
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string FileName = 13;</code>
       */
      public Builder clearFileName() {
        
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>string FileName = 13;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object oldMessageId_ = "";
      /**
       * <code>string OldMessageId = 14;</code>
       */
      public java.lang.String getOldMessageId() {
        java.lang.Object ref = oldMessageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          oldMessageId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string OldMessageId = 14;</code>
       */
      public com.google.protobuf.ByteString
          getOldMessageIdBytes() {
        java.lang.Object ref = oldMessageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          oldMessageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string OldMessageId = 14;</code>
       */
      public Builder setOldMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        oldMessageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string OldMessageId = 14;</code>
       */
      public Builder clearOldMessageId() {
        
        oldMessageId_ = getDefaultInstance().getOldMessageId();
        onChanged();
        return this;
      }
      /**
       * <code>string OldMessageId = 14;</code>
       */
      public Builder setOldMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        oldMessageId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object chatCode_ = "";
      /**
       * <code>string ChatCode = 15;</code>
       */
      public java.lang.String getChatCode() {
        java.lang.Object ref = chatCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          chatCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ChatCode = 15;</code>
       */
      public com.google.protobuf.ByteString
          getChatCodeBytes() {
        java.lang.Object ref = chatCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chatCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ChatCode = 15;</code>
       */
      public Builder setChatCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        chatCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ChatCode = 15;</code>
       */
      public Builder clearChatCode() {
        
        chatCode_ = getDefaultInstance().getChatCode();
        onChanged();
        return this;
      }
      /**
       * <code>string ChatCode = 15;</code>
       */
      public Builder setChatCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        chatCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object chatName_ = "";
      /**
       * <code>string ChatName = 16;</code>
       */
      public java.lang.String getChatName() {
        java.lang.Object ref = chatName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          chatName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ChatName = 16;</code>
       */
      public com.google.protobuf.ByteString
          getChatNameBytes() {
        java.lang.Object ref = chatName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chatName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ChatName = 16;</code>
       */
      public Builder setChatName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        chatName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ChatName = 16;</code>
       */
      public Builder clearChatName() {
        
        chatName_ = getDefaultInstance().getChatName();
        onChanged();
        return this;
      }
      /**
       * <code>string ChatName = 16;</code>
       */
      public Builder setChatNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        chatName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object chatAvatar_ = "";
      /**
       * <code>string ChatAvatar = 17;</code>
       */
      public java.lang.String getChatAvatar() {
        java.lang.Object ref = chatAvatar_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          chatAvatar_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ChatAvatar = 17;</code>
       */
      public com.google.protobuf.ByteString
          getChatAvatarBytes() {
        java.lang.Object ref = chatAvatar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chatAvatar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ChatAvatar = 17;</code>
       */
      public Builder setChatAvatar(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        chatAvatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ChatAvatar = 17;</code>
       */
      public Builder clearChatAvatar() {
        
        chatAvatar_ = getDefaultInstance().getChatAvatar();
        onChanged();
        return this;
      }
      /**
       * <code>string ChatAvatar = 17;</code>
       */
      public Builder setChatAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        chatAvatar_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:InstantMessageInfo)
    }

    // @@protoc_insertion_point(class_scope:InstantMessageInfo)
    private static final com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo();
    }

    public static com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InstantMessageInfo>
        PARSER = new com.google.protobuf.AbstractParser<InstantMessageInfo>() {
      @java.lang.Override
      public InstantMessageInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InstantMessageInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InstantMessageInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InstantMessageInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sunlearning.messanger.proto.ProtoMessage.InstantMessageInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InstantMessageInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InstantMessageInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030InstantMessageInfo.proto\"\366\002\n\022InstantMe" +
      "ssageInfo\022\021\n\tMessageId\030\001 \001(\t\022\022\n\nSenderCo" +
      "de\030\002 \001(\t\022\022\n\nSenderName\030\003 \001(\t\022\024\n\014SenderAv" +
      "atar\030\004 \001(\t\022\024\n\014ReceiverCode\030\005 \001(\t\022\024\n\014Rece" +
      "iverName\030\006 \001(\t\022\026\n\016ReceiverAvatar\030\007 \001(\t\022\024" +
      "\n\014ReceiverType\030\010 \001(\t\022\023\n\013ContentType\030\t \001(" +
      "\t\022\025\n\rStringContent\030\n \001(\t\022\024\n\014BytesContent" +
      "\030\013 \001(\014\022\023\n\013MessageTime\030\014 \001(\003\022\020\n\010FileName\030" +
      "\r \001(\t\022\024\n\014OldMessageId\030\016 \001(\t\022\020\n\010ChatCode\030" +
      "\017 \001(\t\022\020\n\010ChatName\030\020 \001(\t\022\022\n\nChatAvatar\030\021 " +
      "\001(\tB/\n\037com.sunlearning.messanger.protoB\014" +
      "ProtoMessageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_InstantMessageInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_InstantMessageInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InstantMessageInfo_descriptor,
        new java.lang.String[] { "MessageId", "SenderCode", "SenderName", "SenderAvatar", "ReceiverCode", "ReceiverName", "ReceiverAvatar", "ReceiverType", "ContentType", "StringContent", "BytesContent", "MessageTime", "FileName", "OldMessageId", "ChatCode", "ChatName", "ChatAvatar", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
